#pragma once

// This is minified version of original GL/glcorearb.h header originally generated by The Khronos Group Inc.
// Original header can be founded at https://github.com/KhronosGroup/OpenGL-Registry

#include "../gl_format.h"

#ifndef GL_EXT_texture_sRGB_RG8
#define GL_EXT_texture_sRGB_RG8 1
#define GL_SRG8_EXT                       GL_SRG8
#endif /* GL_EXT_texture_sRGB_RG8 */

#ifndef GL_EXT_texture_sRGB_R8
#define GL_EXT_texture_sRGB_R8 1
#define GL_SR8_EXT                        GL_SR8
#endif /* GL_EXT_texture_sRGB_R8 */

#define GL_ALPHA8_EXT                     GL_ALPHA8

